<?php

/**
 * Auto Update, Furasta.Org
 *
 * To be completed. Should check the RSS feed generated by
 * http://furasta.org and check the version etc.
 *
 * @author     Conor Mac Aoidh <conormacaoidh@gmail.com>
 * @license    http://furasta.org/licence.txt The BSD License
 * @version    1.0
 * @package    admin_settings
 */

$javascript='
$(function() {
		$("#tabs").tabs({
			ajaxOptions:{
				error:function(xhr,status,index,anchor) {
					$(anchor.hash).html("Could not load page. Please check your internet connection.");
				}
			}
		});
});
';
$Template->loadJavascript( 'FURASTA_ADMIN_SETTINGS_UPDATE', $javascript );


$content='
<span><span class="header-img" id="header-Auto-Update">&nbsp;</span><h1 class="image-left">Core Update</h1></span>
<br/>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Auto</a></li>
		<li><a href="/_inc/ajax.php?file=admin/settings/update/manual.php">Manual</a></li>
	</ul>
	<div id="tabs-1">
		<div id="tabs-content">
			<p>Could not make a connection. Please use the manual updater.</p>
		</div>
	</div>
</div>
';

$Template->add('content',$content);

?>
