<?php

/**
 * Auto Update, Furasta.Org
 *
 * To be completed. Should check the RSS feed generated by
 * http://furasta.org and check the version etc.
 *
 * @author     Conor Mac Aoidh <conormacaoidh@gmail.com>
 * @license    http://furasta.org/licence.txt The BSD License
 * @version    1.0
 * @package    admin_settings
 */

$head='
<script type="text/javascript">
	$(function() {
		$("#tabs").tabs({
			ajaxOptions:{
				error:function(xhr,status,index,anchor) {
					$(anchor.hash).html("Could not load page. Please check your internet connection.");
				}
			}
		});
	});
</script>
';
$Template->add('head',$head);


$content='
<span><a href="settings.php?page=update&action=auto"><img src="/_inc/img/update.png" class="left"/> <h1 class="image-left">Core Update</h1></a></span>
<br/>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Auto</a></li>
		<li><a href="/_inc/ajax.php?file=admin/settings/update/manual.php">Manual</a></li>
	</ul>
	<div id="tabs-1">
		<div id="tabs-content">
			<p>Could not make a connection. Please use the manual updater.</p>
		</div>
	</div>
</div>
';

$Template->add('content',$content);

?>