<?php

/**
 * Auto Update, Furasta.Org
 *
 * To be completed. Should check the RSS feed generated by
 * http://furasta.org and check the version etc.
 *
 * @author     Conor Mac Aoidh <conormacaoidh@gmail.com>
 * @license    http://furasta.org/licence.txt The BSD License
 * @version    1.0
 * @package    admin_settings
 */

$javascript='
$(function() {
		$("#tabs").tabs({
			ajaxOptions:{
				error:function(xhr,status,index,anchor) {
					$(anchor.hash).html("Could not load page. Please check your internet connection.");
				}
			}
		});
});
';
$Template->loadJavascript( 'FURASTA_ADMIN_SETTINGS_UPDATE', $javascript );


/**
 * check for updates 
 */
$cache_file = 'FURASTA_ADMIN_RSS_UPDATE';

/**
 * fetch update feed
 */
$rss = rss_fetch( 'http://furasta.org/update.xml', 'item' );

foreach( $rss as $feed ){

	if( VERSION < $feed[ 'version' ] ){
		$status = '<p>An update to the CMS is available. Press update below to automatically upgrade to 
				<a href="' . $feed[ 'link' ] . '">' . $feed[ 'title' ] . '</a></p>
				<h3>New Features</h3>
				' . $feed[ 'description' ] . '
				<p><a href="settings.php?page=update&action=verify-auto&file=' . $feed[ 'download' ] . '" class="grey-submit right">Auto Update</a></p>
				<br style="clear:both" />
		';

	}

}

if( $rss == false )
	$status = '<p>Could not make a connection. Please use the manual updater.</p>';

if( !isset( $status ) )
	$status = '<p>No Update Available. Please check back later.</p>';


cache( $cache_file, json_encode( $rss ), 'RSS' );


$content='
<span><span class="header-img" id="header-Auto-Update">&nbsp;</span><h1 class="image-left">Core Update</h1></span>
<br/>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Auto</a></li>
		<li><a href="/_inc/ajax.php?file=admin/settings/update/manual.php">Manual</a></li>
	</ul>
	<div id="tabs-1">
		<div id="tabs-content">
			' . $status . '
		</div>
	</div>
</div>
';

$Template->add('content',$content);

?>
